/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.81
 * Generated at: 2024-10-03 05:14:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Student Learning Management System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        html, body {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            background-image: url('https://images.unsplash.com/photo-1588072432836-e10032774350?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyMDc4MnwwfDF8c2VhcmNofDJ8fHN0dWRlbnRzfGVufDB8fHx8MTYzMzgxNDYyMA&ixlib=rb-1.2.1&q=80&w=1920'); /* Random student-related background image */\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            color: #333; /* Makes the background fixed when scrolling */\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: red;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        nav {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        nav a {\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("        }\r\n");
      out.write("        nav a:hover {\r\n");
      out.write("            background-color: #575757;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 2em;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent background for readability */\r\n");
      out.write("            margin: 1em auto;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 1em;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>Welcome to Student Learning Management System</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"index.jsp\">Home</a>\r\n");
      out.write("        <a href=\"about.jsp\">About</a>\r\n");
      out.write("        <a href=\"contactus.jsp\">Contact</a>\r\n");
      out.write("        <a href=\"login.jsp\">Login</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>Home Page</h2>\r\n");
      out.write("        <p>This is a demo application of Student Learning Management System. A Learning Management System (LMS) is a software application or platform designed to facilitate the delivery, management, and tracking of educational content, training programs, and learning processes. It's used by schools, universities, businesses, and organizations to manage and deliver online or blended learning experiences. Here's an overview of its key features, benefits, and use cases:\r\n");
      out.write("        Key Features of an LMS:\r\n");
      out.write("Course Creation and Management:\r\n");
      out.write("\r\n");
      out.write("Instructors can design courses, create learning materials, and organize lessons.\r\n");
      out.write("Course content can include videos, quizzes, assignments, documents, and presentations.\r\n");
      out.write("User Management:\r\n");
      out.write("\r\n");
      out.write("Admins can manage users (students, teachers, and administrators) and assign roles.\r\n");
      out.write("Instructors can track individual progress and performance, ensuring personalized learning paths.\r\n");
      out.write("Assessment and Evaluation:\r\n");
      out.write("\r\n");
      out.write("Instructors can create and administer quizzes, tests, and assignments.\r\n");
      out.write("The LMS can automatically grade assessments, track scores, and provide feedback.\r\n");
      out.write("Progress Tracking and Reporting:\r\n");
      out.write("\r\n");
      out.write("Learners can track their progress, review grades, and monitor their course completion status.\r\n");
      out.write("Admins and instructors can generate reports on learner performance and participation.\r\n");
      out.write("Interactive Communication:\r\n");
      out.write("\r\n");
      out.write("The platform often supports discussion forums, chat, messaging, and email integration.\r\n");
      out.write("Learners and teachers can collaborate, ask questions, and provide feedback.\r\n");
      out.write("Mobile Learning:\r\n");
      out.write("\r\n");
      out.write("Many LMS platforms are mobile-friendly, enabling learning from any device.\r\n");
      out.write("This flexibility allows users to access course materials on the go, anytime and anywhere.\r\n");
      out.write("Benefits of a Learning Management System:\r\n");
      out.write("Centralized Learning Hub:\r\n");
      out.write("\r\n");
      out.write("All learning materials and resources are stored in one platform, making it easier for learners and instructors to access and manage content.\r\n");
      out.write("Scalable Learning Environment:\r\n");
      out.write("\r\n");
      out.write("Whether you are training a few employees or educating thousands of students, an LMS can scale to meet diverse learning needs.\r\n");
      out.write("Flexibility and Accessibility:\r\n");
      out.write("\r\n");
      out.write("Learners can access content at their own pace, making learning more flexible and personalized. This is particularly important for remote and distance learning.\r\n");
      out.write("Cost-Efficient:\r\n");
      out.write("\r\n");
      out.write("By digitizing course materials and reducing the need for physical infrastructure, an LMS can significantly reduce the costs associated with traditional learning environments.\r\n");
      out.write("Customizable Learning Paths:\r\n");
      out.write("\r\n");
      out.write("Instructors can tailor courses and learning paths to the needs of individual learners, promoting personalized learning experiences.\r\n");
      out.write("Collaboration and Engagement:\r\n");
      out.write("\r\n");
      out.write("Through discussion boards, chat rooms, and interactive assessments, learners can collaborate and engage with peers and instructors more effectively.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("        &copy; 2024 Student Learning Management System\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
